name: Research Forum
favicon: null
layout_spectrum: 0.6741790126543492
typography_spectrum: 0.17831517988815904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2ffff'
    - '#004787'
    - '#75c44c'
    - '#36bac8'
    - '#6b7276'
  brandStrength: 0.25
  lightness: 0.6230635156389326
  saturation: 0.8627233263105154
  rhythmicContrast: 0.9530536187812686
purpose: []
